[package]
name = "coil-debug"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "coil-debug"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
machine = { path = "../machine", default-features = false, features = ["debugger"] }
compiler = { path = "../compiler", default-features = false, features = ["dissect"] }
reporting = { path = "../reporting" }
coil-cli = { path = "../coil-cli", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = "1"

[lib]
path = "src/lib.rs"

[features]
default = ["time"]
time = ["machine/time", "compiler/time", "coil-cli/time"]
