//! What users see when a macro goes wrong. Fixtures live in
//! `tests/compile_fail/macro_*.hy` (so `coil test` also checks they fail);
//! providers in `examples/src/derive_macros*.hy`.

use std::io::Write;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use compiler::Pipeline;
use reporting::ReportConfig;

#[derive(Clone, Default)]
struct Buf(Arc<Mutex<Vec<u8>>>);

impl Write for Buf {
    fn write(&mut self, b: &[u8]) -> std::io::Result<usize> {
        self.0.lock().unwrap().extend_from_slice(b);
        Ok(b.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

/// Compile `tests/compile_fail/<name>.hy`; return rendered diagnostics.
fn compile_fail(name: &str) -> String {
    comptime::install();
    let buf = Buf::default();
    let mut pipeline = Pipeline::with_reporter(ReportConfig::default(), Box::new(buf.clone()));
    pipeline.bind_project_root(repo(), vec![PathBuf::from("examples/src")]);
    let file = repo().join("tests/compile_fail").join(format!("{name}.hy"));
    let result = pipeline.compile_src_from_file(file.to_str().unwrap());
    let _ = pipeline.finish_reporting();
    let out = String::from_utf8(buf.0.lock().unwrap().clone()).unwrap();
    assert!(result.is_err(), "{name} compiled:\n{out}");
    out
}

fn expect(name: &str, needles: &[&str]) {
    let out = compile_fail(name);
    for n in needles {
        assert!(out.contains(n), "{name}: missing `{n}` in:\n{out}");
    }
}

#[test]
fn self_use_is_a_staging_error() {
    expect("macro_self_use", &["`Local` is a derive declared in this module"]);
}

#[test]
fn unknown_helper_attribute() {
    expect("macro_unknown_helper", &["Unknown attribute `json`", "attrs(json)"]);
}

#[test]
fn runaway_macro_hits_step_budget() {
    expect("macro_runaway", &["derive `Spin` failed", "step budget exhausted"]);
}

#[test]
fn host_access_is_denied() {
    expect("macro_host_denied", &["`env_var` is not available to compile-time macros"]);
}

#[test]
fn panic_message_is_shown() {
    expect("macro_panic", &["Refuse cannot derive C"]);
}

#[test]
fn generated_type_error_points_at_derive() {
    expect(
        "macro_generated_type_error",
        &[
            "Type mismatch",
            "#[derive(BadType)]",
            "in code generated by derive `BadType`",
        ],
    );
}

#[test]
fn generated_syntax_error_shows_code() {
    expect("macro_generated_syntax_error", &["produced code that does not parse", "impl {"]);
}

#[test]
fn duplicate_import_is_rejected() {
    expect("macro_duplicate_import", &["imported from more than one module"]);
}

#[test]
fn expansion_cycle_is_reported() {
    expect("macro_cycle", &["macro expansion cycle"]);
}

#[test]
fn attribute_macro_arguments_are_checked() {
    expect("macro_attr_missing_arg", &["missing argument `by`"]);
}

#[test]
fn qualified_impl_head_in_source() {
    expect(
        "macro_qualified_impl",
        &[
            "module-qualified trait `derive_macros::Summary` in an `impl` head is only written by macros",
            "`use derive_macros::Summary;` and write `impl Summary for …`",
        ],
    );
}
