[package]
name = "coil-dissect"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "coil-dissect"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
parser = { path = "../parser" }
compiler = { path = "../compiler", default-features = false, features = ["dissect"] }
reporting = { path = "../reporting" }
coil-cli = { path = "../coil-cli", default-features = false }

[features]
default = []
