[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[features]
default = ["crypto", "time", "tls"]
dissect = []
crypto = ["machine/crypto"]
time = ["machine/time"]
tls = ["machine/tls"]
pratt = []

[dependencies]
common = { path = "../common" }
machine = { path = "../machine", default-features = false }
parser = { path = "../parser" }
reporting = { path = "../reporting" }
rkyv = "0.8.12"
serde = { version = "1", features = ["derive"] }
bincode = "1"

[dev-dependencies]
machine = { path = "../machine", default-features = false, features = ["vm_profile"] }
proptest = "1"
libc = "0.2"
rcgen = "0.13"
serde_json = "1"

[[test]]
name = "dissect"
required-features = ["dissect"]
